DATASET:
  IMG_RES: 224
  VAL:
    FRAME_SKIP: 5
  TEST:
    FRAME_SKIP: 10
NUM_WORKERS: 8
OPTIMIZER:
  TYPE: 'adam'
  LR: 6.0e-5
  WD: 0.0
LOSS:
  KEYPOINT_3D_LOSS_WEIGHT: 0.
  KEYPOINT_2D_LOSS_WEIGHT: 5.
  SHAPE_LOSS_WEIGHT: 0. # 0.05
  LOSS_WEIGHT: 60.
  DEPTH_LOSS_WEIGHT: 5.
  CAM_LOSS_WEIGHT: 1.
TRAIN:
  MAX_EPOCH: 1
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False

SEED_VALUE: 358053
