DATASET:
  IMG_RES: 224
NUM_WORKERS: 8
OPTIMIZER:
  LR: 6.0e-5
  WD: 0.0
LOSS:
  KEYPOINT_3D_LOSS_WEIGHT: 300.
  KEYPOINT_2D_LOSS_WEIGHT: 300.
  DEPTH_LOSS_WEIGHT: 5.
  CAM_LOSS_WEIGHT: 60.
TRAIN:
  MAX_EPOCH: 1
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False

SEED_VALUE: 358053
